[package]
name = "rebook-formats"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
encoding_rs.workspace = true
iepub.workspace = true
quick-xml.workspace = true
rebook-html = { path = "../html" }
rebook-publication = { path = "../publication" }
roxmltree.workspace = true
sha2.workspace = true
thiserror.workspace = true
zip.workspace = true

[lints]
workspace = true
